---
- name: reload postgresql
  shell: systemctl reload "postgresql@{{ postgres_version }}-main" || systemctl restart "postgresql@{{ postgres_version }}-main"
  listen: reload postgresql
  changed_when: true

- name: restart postgresql
  shell: systemctl restart "postgresql@{{ postgres_version }}-main"
  listen: restart postgresql
  changed_when: true