postgres_version: "14"


postgres_admin_user: "postgres"
postgres_admin_pass: ""

postgresql_group: "postgres"


postgresql_data_dir: "/mnt/postgresql/data"
postgresql_effective_log_dir: "/mnt/postgresql/logs"
postgresql_bin_path: "/usr/lib/postgresql/{{ postgres_version }}/bin"

